name: ⚡️ Update Status. ⚡️
on:
  workflow_dispatch:
  schedule:
      - cron: "0 */24 * * *"
jobs:
  update-readme-with-projects:
    name: 🏃‍♂️ run the bot 🏃‍♂️
    runs-on: ubuntu-latest
    steps:
    
      - uses: jainamoswal/BotStatus@main
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          BOTS: https://api.npoint.io/27bde7571a357dd87105
          SESSION: ${{ secrets.SESSION }} 
          APP_ID: ${{ secrets.APP_ID }} 
          API_HASH: ${{ secrets.API_HASH }} 
          IDS: -1001407470646:3 
          EDIT_IN_TELEGRAM: True
          EDIT_IN_REPO: True
          
      - name: Get status
        run: echo $output
        
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_TOKEN }}
          repository: ${{ secrets.REPO }}
          event-type: update-file
          client-payload: '{"status": "${{ env.output }}"}'  
 

          
     
